//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uhebka_Mubarakshin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Academic
    {
        public int ID_Academic { get; set; }
        public string Familia { get; set; }
        public string Name { get; set; }
        public string Othestvo { get; set; }
        public Nullable<System.DateTime> Data_Rojdenia { get; set; }
        public string Specialiazacia { get; set; }
        public string God_prisvoenia_zvania { get; set; }
    }
}
