//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uhebka_Mubarakshin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sotrudnik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sotrudnik()
        {
            this.Injener = new HashSet<Injener>();
            this.Zav_kafedra = new HashSet<Zav_kafedra>();
        }
    
        public int Tab_Number_Sot { get; set; }
        public string Shifr { get; set; }
        public string Familia { get; set; }
        public string Doljnost { get; set; }
        public Nullable<decimal> Zarplata { get; set; }
        public string Shef { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Injener> Injener { get; set; }
        public virtual Kafedra Kafedra { get; set; }
        public virtual Prepodovatel Prepodovatel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zav_kafedra> Zav_kafedra { get; set; }
    }
}
