//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uhebka_Mubarakshin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Strana
    {
        public int ID_Strana { get; set; }
        public string Nazvanie { get; set; }
        public string Stolica { get; set; }
        public Nullable<decimal> Plocad { get; set; }
        public Nullable<decimal> Naselenie { get; set; }
        public string Kontinent { get; set; }
    }
}
