//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uhebka_Mubarakshin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zav_kafedra
    {
        public int ID_Zav_Kafedra { get; set; }
        public int Tab_Nomer { get; set; }
        public Nullable<int> Staj { get; set; }
    
        public virtual Sotrudnik Sotrudnik { get; set; }
    }
}
